#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
	conf.check_cfg(package='jack', uselib_store='JACK', args='--cflags --libs', atleast_version='1.9.2')
	conf.env['LIB_NCURSES'] = ['ncurses']

def build(bld):
	bld.new_task_gen(
		features = 'cxx cprogram',
		source = 'jack.cpp loop.cpp mloop.cpp notecache.cpp ringbuffer.cpp ui.cpp',
		target = 'mloop',
		uselib = 'JACK NCURSES')
